### ISSUE TITLE
Recursive option needed

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-filter-de_dot#7]
Recursive de-dotting will be slow, but we probably need to add the option

**Comment by janbernhardt** [comment]
This enhancement would be very valuable for us.

What about filter pattern to only do sub-level filtering where needed.
For example:

`[*] : Filter all root level fields`
`[*][*] : Filters all recursive (sub)fields`
`[group1][*] : Filters all direct sub-fields of group1`
`[group1][*][*] : Filters all recursive sub-fields of group1`
`[group1][dotted.field] : Filters only dotted.field inside of group1`
`[group1][dotted.field][*] : Filters all direct sub-fields of dotted.field inside of group1`

**Comment by matthughes** [comment]
So right now it only works on top level fields?  I have a bunch of fields under: `[data][metadata]`.  I just assumed that work transform every field immediately under (not recursive) `[data][metadata]`.  If that doesn't work, I don't understand what is the purpose of the `fields` value.  You can't specify a field with periods in it, can you?

**Comment by rtoma** [comment]
Have a look at https://discuss.elastic.co/t/field-name-cannot-contain/33251/39 - this comment contains the code for recursive renaming.

**Comment by guenhter** [comment]
The ruby script of the given link works just fine, but no nesting is possible. So we appreciate it, if this would be done by this plugin.

**Comment by spider-network** [comment]
+1

**Comment by andrewvc** [comment]
Are you all using this for ES integration? In ES 2.4+ you can enable dots in field names, and in 5.0 they should work by default.

**Comment by andrewvc** [comment]
Here's a link to the doc on the subject: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html

**Comment by mikelorant** [comment]
Merging issues have been resolved for #22 with a new pull request #23. To make #22 pass, a recheck needs to be done for a CLA refresh.

**Comment by jsvd** [comment]
solved by #24 (with retained authorship) and published as https://rubygems.org/gems/logstash-filter-de_dot/versions/1.1.0
